### ISSUE TITLE
Failed to activate the npm-autocomplete package

### ISSUE THREAD

**Issue by danielpetrovaliev** [capaj/npm-autocomplete#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [npm-autocomplete](https://github.com/capaj/npm-autocomplete) package, v0.1.1
### Stack Trace

Failed to activate the npm-autocomplete package

```
At Arguments to path.join must be strings

TypeError: Arguments to path.join must be strings
  at f (path.js:201:13)
  at Object.filter (native)
  at Object.win32.join (path.js:206:38)
  at Object.npmAutocomplete.provide (C:\Users\petrovaliev95\.atom\packages\npm-autocomplete\lib\npm-autocomplete.js:55:21)
  at Package.module.exports.Package.activateServices (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:355:117)
  at Package.module.exports.Package.activateNow (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:243:16)
  at C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:221:30
  at Package.module.exports.Package.measure (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:167:15)
  at Package.module.exports.Package.activate (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\package-manager.js:465:21)
  at C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:268:29
  at exit (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\node_modules\settings-view\lib\package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:63:47)
  at ChildProcess.<anonymous> (C:\Users\petrovaliev95\AppData\Local\atom\app-0.187.0\resources\app\src\buffered-process.js:85:18)
  at ChildProcess.emit (events.js:119:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```
### Commands

```
     -2:32.0 core:confirm (atom-text-editor.editor.mini)
     -2:06.1 application:new-file (div.settings-view.pane-item)
     -0:47.2 core:select-all (atom-text-editor.editor.mini)
     -0:46.5 core:paste (atom-text-editor.editor.mini)
     -0:43.0 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "themes": [
      "unity-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v1.4.4
npm-autocomplete, v0.1.1
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by capaj** [comment]
yeah this happens when you don't have a project opened. I will push a fix this evening with few other improvements.

**Comment by capaj** [comment]
Fix verified on my Windows machine.
