### ISSUE TITLE
Failed to load the npm-autocomplete package

### ISSUE THREAD

**Issue by leifdalan** [capaj/npm-autocomplete#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [npm-autocomplete](https://github.com/capaj/npm-autocomplete) package, v0.1.2
### Stack Trace

Failed to load the npm-autocomplete package

```
At Illegal invocation

TypeError: Illegal invocation
    at plain (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/node_modules/witwip/node_modules/debug/lib/debug.js:130:19)
    at find (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/node_modules/witwip/witwip.js:102:3)
    at witwip (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/node_modules/witwip/witwip.js:50:5)
    at getPackageJSONpath (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/index.js:79:3)
    at getPackageDependencies (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/index.js:87:3)
    at Object.module.exports.install (/Users/leifdalan/.atom/packages/npm-autocomplete/node_modules/atom-package-dependencies/index.js:8:5)
    at Object.<anonymous> (/Users/leifdalan/.atom/packages/npm-autocomplete/lib/npm-autocomplete.js:6:5)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ],
    "disabledPackages": [
      "jsformat",
      "tabs",
      "tree-view",
      "eslint"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v0.4.0
autocomplete-css, v0.6.0
autocomplete-plus, v2.7.1
color-picker, v1.5.0
ember-snippets, v1.0.0
javascript-snippets, v1.0.0
language-freemarker, v0.2.0
language-jade, v0.3.0
language-javascript-better, v1.1.0
language-javascript-jsx, v0.3.1
linter, v0.12.0
npm-autocomplete, v0.1.2
react, v0.10.1
seti-ui, v0.6.3
styleguide, v0.44.0
sublime-tabs, v0.5.2

# Dev
No dev packages
```

**Comment by capaj** [comment]
this looks like a bug in https://github.com/travs/atom-package-dependencies, could you repost it there please?
